### ISSUE TITLE
[工作流程图]对节点编辑，左右双击都能进行编辑。确认一个键进行编辑

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/itsm#1]
[工作流程图]对节点编辑，左右双击都能进行编辑。确认一个键进行编辑

![image](https://user-images.githubusercontent.com/22296563/30678288-c15662da-9ec3-11e7-8598-8025f341db36.png)

**Comment by hengwei-lhm** [comment]
fixed 右键双击不会弹出菜单

**Comment by xiauye** [comment]
已确认
