### ISSUE TITLE
[请求管理]请求流程删除请求和合并请求加上特定的用户才能操作的权限

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#100]
请求流程删除请求和合并请求加上特定的用户才能操作的权限

**Comment by hengwei-ly** [comment]
这个需求需要讨论：
目前合并请求不需要任何权限，合并操作发生时会记录合并人（审计日志里面记录）
请求合并不适用于流程管理的权限，待确认后再进行修改

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180123_3203_x64.exe  版本确认，close处理。
