### ISSUE TITLE
[服务管理]安装时、提示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#101]
Migrating schema "public" to version 4.2.023 - Update ITSM ThemeToSubject
WARNING: DB: 标识符"rename_solution_theme_id_to_solution_subject_id_on_tpt_itsm_solutions"将会被截断为"rename_solution_theme_id_to_solution_subject_id_on_tpt_itsm_sol" (SQL State: 42622 - Error Code: 0)
WARNING: DB: 标识符"rename_solution_theme_id_to_solution_subject_id_on_tpt_itsm_solutions"将会被截断为"rename_solution_theme_id_to_solution_subject_id_on_tpt_itsm_sol" (SQL State: 42622 - Error Code: 0)
ERROR: Migration of schema "public" to version 4.2.023 - Update ITSM ThemeToSubject failed! Changes successfully rolled back.
ERROR: 
Migration V4_2_023__Update_ITSM_ThemeToSubject.sql failed
---------------------------------------------------------
SQL State  : 42701
Error Code : 0
Message    : 错误: 关系 "solution_subject_id" 的属性 "tpt_itsm_solutions" 已经存在
  在位置：SQL 语句 "ALTER TABLE IF EXISTS public.tpt_itsm_solutions RENAME solution_theme_id  TO solution_subject_id"
在SQL语句的第4行的PL/pgSQL函数rename_solution_theme_id_to_solution_subject_id_on_tpt_itsm_sol()
Location   : db/migration/V4_2_023__Update_ITSM_ThemeToSubject.sql (C:\Program Files\hengwei\file:\C:\Program Files\hengwei\runtime_env\flyway\..\..\lib\server_biz\extreme-biz-3.3.1.jar!\db\migration\V4_2_023__Update_ITSM_ThemeToSubject.sql)
Line       : 14
Statement  : SELECT rename_solution_theme_id_to_solution_subject_id_on_tpt_itsm_solutions()

exit status 1

**Comment by hengwei-ly** [comment]
已修复

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180123_3203_x64.exe  版本确认，close处理。
