### ISSUE TITLE
[解决方案]添加解决方案时、提示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#103]
添加解决方案时、提示错误

![default](https://user-images.githubusercontent.com/28615156/34926015-ccef0636-f9e7-11e7-842d-29a6a46cde1f.png)

**Comment by hengwei-ly** [comment]
已完成

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180123_3203_x64.exe  版本确认，close处理。
