### ISSUE TITLE
[解决方案]添加解决方案失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#106]
添加解决方案失败

![default](https://user-images.githubusercontent.com/28615156/35140439-335b4ab8-fd32-11e7-94c0-dee8959e1fe3.png)

**Comment by hengwei-ly** [comment]
更新表的sql未打包  已解决

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180123_3203_x64.exe  版本确认，close处理。
