### ISSUE TITLE
[ITSM内部错误]流程图取消报错

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/itsm#109]
新建流程图还未报错时点取消按钮出现
如下是报错信息
-------------------

Not Found

No matching route found: /hengwei/itsm/Workflows/%22/hengwei/itsm/requesttypes/edit?hasCompletedSteps=0\u0026id=8\u0026startIndex=3%22

**Comment by hengwei-ly** [comment]
已解决  并增加一个返回按钮  点击返回按钮回到原界面  点击取消只是取消编辑  新建或者保存成功也会跳转到原页面

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3210_x64.exe 版本确认，close处理。
