### ISSUE TITLE
[服务管理]配置流程图宽度太大、界面没有滚动条

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#110]
配置流程图宽度太大、界面没有滚动条

![default](https://user-images.githubusercontent.com/28615156/35323630-287ca89e-0129-11e8-8611-4ecf9b98a8c4.png)

**Comment by hengwei-ly** [comment]
点击左上角第四个按钮 可以拖动已编辑的流程，第五个和第六个按钮可以缩放显示流程图，所以不需要向右的滚动条
