### ISSUE TITLE
[服务管理]编辑请求类型中、直接点击配置流程图、流程图的信息为空

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#112]
1.编辑请求类型中、直接点击配置流程图、流程图的信息为空

![default](https://user-images.githubusercontent.com/28615156/35372892-22a0f73c-01d7-11e8-8129-ae475f9330e4.png)

**Comment by hengwei-ly** [comment]
贴图  方便重现

**Comment by hengwei-ly** [comment]
其实这个不是bug；
两种解决方案：

1. 限制流程标题的点击事件，使用户只能按照页面下方的上一步下一步点击

2.直接修改 
暂选第二种方案

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3210_x64.exe 版本确认，close处理。
