### ISSUE TITLE
[服务管理]在请求中添加新的解决方案、主题没有时无法选择

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#116]
1.在请求中添加新的解决方案、主题没有时无法选择
2.能不能加个添加按钮、弹个窗口添加新的主题

![default](https://user-images.githubusercontent.com/28615156/35431626-272ff80c-02b8-11e8-942a-4bceaea678be.png)

**Comment by hengwei-ly** [comment]
已解决
在程序初始化检查当前方案主题，如果没有主题，会默认添加一条"无主题"的主题
![image](https://user-images.githubusercontent.com/26591247/35723397-10a8613c-0835-11e8-9c16-5e78c63a3b39.png)

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180211_3262_x64.exe  版本确认，close处理。
