### ISSUE TITLE
[服务管理]在请求信息中非请求明细页面、点击关闭事件的流程、中止或关闭原因:窗口不弹出

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#118]
1.在请求信息中非请求明细页面、点击关闭事件的流程、中止或关闭原因:窗口不弹出

![default](https://user-images.githubusercontent.com/28615156/35432100-f8584f50-02b9-11e8-99e6-29993707f201.png)

**Comment by hengwei-ly** [comment]
已解决

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
