### ISSUE TITLE
[服务管理]流程图中支持组里套组的选择

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#119]
1.流程图中支持组里套组的选择

![default](https://user-images.githubusercontent.com/28615156/35490511-07a0c87a-04db-11e8-99a1-f4e540c6d719.png)

**Comment by hengwei-ly** [comment]
不支持组套组  只能做查询出组里所有的人  并且包括子分组的人

**Comment by hengwei-ly** [comment]
已完成 ，现在查询组成员会包含所有子组的成员，判断成员所属组会查询当前成员所在组以及所有父组

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
