### ISSUE TITLE
[请求人列表]添加、编辑，是否为VIP无法修改，应该勾选：true，没有勾选：false

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/itsm#12]
[请求人列表]添加、编辑，是否为VIP无法修改，应该勾选：true，没有勾选：false

![image](https://user-images.githubusercontent.com/22296563/30789258-db45143c-a1d6-11e7-8e22-40b83363e015.png)

**Comment by hengwei-ly** [comment]
请求人列表所有与提交有关的操作都已经做了修改

**Comment by xiauye** [comment]
为true在编辑时，应该是勾选状态

**Comment by hengwei-ly** [comment]
这个bug是老梅那边的  晚一点我跟他说一下

**Comment by hengwei-ly** [comment]
已解决

**Comment by xiauye** [comment]
bug没有解决，还是同样的问题

**Comment by hengwei-ly** [comment]
已解决
