### ISSUE TITLE
[华东电网]增加一个按照流程中分配人员的查询统计

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#121]
1.增加一个按照流程中分配人员的查询统计

**Comment by hengwei-ly** [comment]
已完成   在报表中实现
![image](https://user-images.githubusercontent.com/26591247/35846544-0c3c03f4-0b52-11e8-85f6-48ccaa586a15.png)

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180207_3243_x64.exe  版本确认，close处理。
