### ISSUE TITLE
[新建流程图]提示信息将选择流程图压下去了。不能进行选择。

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/itsm#13]
[新建流程图]提示信息将选择流程图压下去了。不能进行选择。做一个几秒钟自动消失提示信息
![image](https://user-images.githubusercontent.com/22296563/30792996-3a4a39ca-a1f1-11e7-9407-1c6e83bf0fa7.png)

**Comment by hengwei-ly** [comment]
已修改为弹窗格式的提醒
