### ISSUE TITLE
[华东电网]服务管理主页处理请求后、跳转到主页面

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#132]
1.用户在服务管理主页当前用户下的请求处理后、跳转页面还是跳转到主页。
2.原因：现在主页处理请求后、会跳转到请求管理或者两票管理菜单下、用户再次处理下一个请求时、寻找当前用户下的请求比较麻烦、需要跳转到主页或者使用查找功能。

**Comment by runner-mei** [comment]
fixed
