### ISSUE TITLE
[待办事件]待办事件中请求的数量与服务管理中待处理的数量不符

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#133]
1.待办事件中请求的数量与服务管理中待处理的数量不符

待办事件中数量：29：
![default](https://user-images.githubusercontent.com/28615156/39287230-454dfeb8-4955-11e8-8df5-5c95fcd06f8d.png)
服务管理数量：
![default](https://user-images.githubusercontent.com/28615156/39287236-4e9c1068-4955-11e8-8f02-6e000f3c684f.png)

**Comment by runner-mei** [comment]
fixed
