### ISSUE TITLE
[菜单显示不出来]按菜单伸缩按钮，菜单没有显示出来

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/itsm#14]
[菜单显示不出来]按菜单伸缩按钮，菜单没有显示出来
![image](https://user-images.githubusercontent.com/22296563/30793805-cd08eb4e-a1f6-11e7-9c5f-3dcd0242aebe.png)

**Comment by hengwei-ly** [comment]
目前发现三个地方又这个问题：主页  仪表板  报表 ； 已解决

**Comment by xiauye** [comment]
已确认

**Comment by xiauye** [comment]
本问题又出现了

**Comment by hengwei-ly** [comment]
没有登录导致  正常登录不会有这个问题
