### ISSUE TITLE
[服务管理]缺陷管理中、缺陷任务关联的两票删除后、点击查看按钮查看缺陷信息失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#142]
1.缺陷管理中、缺陷任务关联的两票删除后、点击查看按钮查看缺陷信息失败

![default](https://user-images.githubusercontent.com/28615156/39735235-45480a24-52ad-11e8-905d-3118e721f48b.png)

**Comment by runner-mei** [comment]
fixed
