### ISSUE TITLE
[工作流程图]节点名称同名时提示一下

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/itsm#15]
[工作流程图]节点名称同名时提示一下
![image](https://user-images.githubusercontent.com/22296563/30794254-b22f35fa-a1f9-11e7-99f1-0f8461026888.png)

**Comment by hengwei-ly** [comment]
有提示  名称填写框变红的时候鼠标放在框上就能看见

**Comment by hengwei-lhm** [comment]
fixed

**Comment by xiauye** [comment]
已确认
