### ISSUE TITLE
[解决方案]利用关键字搜索不出来内容

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/itsm#17]
[解决方案]利用关键字搜索不出来内容
![image](https://user-images.githubusercontent.com/22296563/30796540-189ea838-a205-11e7-8913-8e3a5577e132.png)

**Comment by hengwei-ly** [comment]
已解决:
![image](https://user-images.githubusercontent.com/26591247/34379070-2f6d7d5a-eb34-11e7-8df7-8846551f9b33.png)
同时实现按照标题模糊查询和按照关键字完整查询
![image](https://user-images.githubusercontent.com/26591247/34379093-59e8ac58-eb34-11e7-975d-0b7b3b7bea5a.png)

![image](https://user-images.githubusercontent.com/26591247/34379119-879b796e-eb34-11e7-9175-8cfc0753b2b9.png)

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3210_x64.exe 版本确认，close处理。
