### ISSUE TITLE
[选择用户]负责人、申请人，最后面有三个是空值选择

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/itsm#18]
[选择用户]负责人、申请人，最后面有三个是空值选择
2、进行用户选择时，可以进行搜索用户选择
![image](https://user-images.githubusercontent.com/22296563/30797428-96d16a4e-a208-11e7-9e92-8d9c173a9969.png)

**Comment by hengwei-ly** [comment]
这个不是bug   是当前用户管理模块与运维平台没有完全整合导致的  自己在用户管理模块创建的用户要加上昵称字段值才会显示名字，这里显示的就是昵称。

**Comment by xiauye** [comment]
ok
