### ISSUE TITLE
[报表管理]报表统计，当天的报表统计不出来

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/itsm#20]
[报表管理]报表统计，当天的报表统计不出来
![image](https://user-images.githubusercontent.com/22296563/30798417-2c1c0a98-a20c-11e7-9c04-37b5610464cd.png)

**Comment by hengwei-ly** [comment]
如图所示：原先统计的是结束日期的00:00 即：2017-09-25 00:00:00  现在改为 2017-09-25 23:59:59

**Comment by xiauye** [comment]
已确认
