### ISSUE TITLE
[仪表板]请求方式没有设置所统计的请求方式，统计请求方式错误

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/itsm#21]
[仪表板]请求方式没有设置所统计的请求方式，统计请求方式错误
![image](https://user-images.githubusercontent.com/22296563/30798923-c25eff50-a20d-11e7-9dea-a6f5f7e2bf92.png)
![image](https://user-images.githubusercontent.com/22296563/30798969-e3331068-a20d-11e7-9bff-f41b4871a137.png)

**Comment by hengwei-ly** [comment]
已解决

**Comment by xiauye** [comment]
已确认
