### ISSUE TITLE
[变更]新建变更报错，但是变更已经创建

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/itsm#23]
[变更]新建变更报错，但是变更已经创建
![image](https://user-images.githubusercontent.com/22296563/30802283-85750052-a218-11e7-9c76-646e6e1eb6fd.png)

**Comment by hengwei-ly** [comment]
已修复

**Comment by xiauye** [comment]
bug还是存在

**Comment by xiauye** [comment]
已确认
