### ISSUE TITLE
[变更]变更关联已经关闭的请求会报错

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/itsm#24]
[变更]变更关联请求，报错
![image](https://user-images.githubusercontent.com/22296563/30839016-ab1f9e8c-a2a1-11e7-90c4-a5610d7f51d5.png)

**Comment by hengwei-ly** [comment]
这个暂时没有发现问题；关联失败是因为请求1本身有错误，按正常流程创建的请求和变更是可以正常关联的(新建请求1，新建变更1)

**Comment by xiauye** [comment]
变更关联已经请求会报错

**Comment by xiauye** [comment]
变更关联已经关闭的请求会报错

**Comment by hengwei-ly** [comment]
这是已关闭的请求或者变更不能再进行访问  已修复，另外后面可能会做关闭后的项不能进行操作  只能查看（权限管理中再做  暂时不做，可提）

**Comment by xiauye** [comment]
已确认
