### ISSUE TITLE
[变更]变更进行关联请求会跳转到请求页面，应该还在变更页面。请求关联变更也是一样

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/itsm#25]
[变更]变更进行关联请求会跳转到请求页面，应该还在变更页面。请求关联变更也是一样

**Comment by hengwei-ly** [comment]
原先的跳转规则是：关联到请求的跳转到请求页面，关联到变更的跳转到变更页面；
修改后的跳转规则是：在哪个页面进行关联操作，就跳转到哪个页面

**Comment by xiauye** [comment]
已确认
