### ISSUE TITLE
两票的表单应该连续创建，只有同时具备两票的工单才能流转到下一步

### ISSUE THREAD

**Issue by hengwei-ly** [three-plus-three/itsm#29]
两票表示一个流程，领导审核时必须同时包含两票，所以表单应该连续创建

**Comment by hengwei-ly** [comment]
received

**Comment by hengwei-ly** [comment]
修改为：不一定连续创建，但是要添加限制条件，必须某个值有值才能进行下一步

**Comment by hengwei-ly** [comment]
ok  做了判断，现在实现了两票同时存在才可以流转到下一步

**Comment by hengwei-ly** [comment]
这个是在流程图上加的限制条件  但是当前流程图的页面没有增加按钮  所以是以sql方式导入

**Comment by hengwei-test** [comment]
已经确认，close处理
