### ISSUE TITLE
[工作流程图]新建流程图，在没有输入任何名称信息，不能进行关闭

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/itsm#3]
[工作流程图]1、新建流程图，在没有输入任何名称信息，不能进行关闭
                     2、添加一个确认，取消按钮

![image](https://user-images.githubusercontent.com/22296563/30678418-b998b984-9ec4-11e7-831f-a58a62e4024b.png)

**Comment by hengwei-lhm** [comment]
调用new方法的时候把name值加上
 designer.new(function (data) {
            data.name = getDefaultName()
        })

**Comment by hengwei-ly** [comment]
调优完成；
目前 请求工作流的创建：默认名为"请求流程图"+数字  
        变更工作流的创建：默认名为"变更流程图"+数字
数字自动增大  如果有124这样的数字  下一个插入的是3 可以保证默认名称不会重复

**Comment by xiauye** [comment]
已确认
