### ISSUE TITLE
[两票管理]两票管理的高级搜索查询失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#39]
1.两票管理的高级搜索查询失败
2.查询编号的查询同样出现此现象

![1508906818 1](https://user-images.githubusercontent.com/28615156/31980962-a5b2bbf8-b982-11e7-907c-3fd345115e6b.jpg)

**Comment by hengwei-ly** [comment]
ok

**Comment by hengwei-test** [comment]
已经确认，close处理
