### ISSUE TITLE
[两票管理]未选择两票时，点击删除按钮、删除提示窗中点击确定按钮提示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#41]
1.未选择两票时，点击删除按钮、删除提示窗中点击确定按钮提示错误

![1508907539 1](https://user-images.githubusercontent.com/28615156/31981233-88aa1a9a-b984-11e7-822f-4bc264e19bde.jpg)

**Comment by hengwei-ly** [comment]
ok  所有其他的模块也都存在这个问题  暂时只更新了两票管理和请求

**Comment by hengwei-test** [comment]
已经确认，close处理
