### ISSUE TITLE
[解决方案]已弃用的解决方案，还能在请求解决方案中进行选择

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/itsm#5]
[解决方法]已弃用的解决方案，还能在请求解决方案中进行选择

![image](https://user-images.githubusercontent.com/22296563/30689371-5559af58-9ef3-11e7-9d5d-598725d42e14.png)

![image](https://user-images.githubusercontent.com/22296563/30689441-853123aa-9ef3-11e7-9adf-e5cd0f7ee018.png)

**Comment by hengwei-ly** [comment]
已解决

**Comment by xiauye** [comment]
已确认
