### ISSUE TITLE
[SLA]新建SLA时匹配规则，第一次添加匹配规则成功之后进行删除，再进行添加一样的配置规则，是匹配规则已经存在

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/itsm#6]
[SLA]新建SLA时匹配规则，第一次添加匹配规则成功之后进行删除，再进行添加一样的配置规则，是匹配规则已经存在

![image](https://user-images.githubusercontent.com/22296563/30726698-fc4b71c6-9f7e-11e7-9af4-751277b2e714.png)
![image](https://user-images.githubusercontent.com/22296563/30726852-fdd27aac-9f7f-11e7-93a1-392a98f791f3.png)

**Comment by hengwei-ly** [comment]
已解决  需要测试：新增和编辑的时候添加条件 然后删除条件  保存后，保存的条件是否正确

**Comment by xiauye** [comment]
已确认
