### ISSUE TITLE
[两票管理]创建操作票后，点击编辑按钮，在点击工作票、页面中多选列表框格式错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#60]
1.创建操作票后，点击编辑按钮，在点击工作票、页面中多选列表框格式错误

![1509526333 1](https://user-images.githubusercontent.com/28615156/32267109-1520e558-bf25-11e7-9bea-34a6ed2779e5.jpg)

**Comment by hengwei-ly** [comment]
fixed
