### ISSUE TITLE
[采购管理]左侧菜单栏中点击采购管理按钮、提示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#65]
1.左侧菜单栏中点击采购管理按钮、提示错误

![3 jq9 xzx0zwfafq1qoslf](https://user-images.githubusercontent.com/28615156/32586350-0d21dc68-c53d-11e7-8817-85c288af72cc.png)

**Comment by hengwei-ly** [comment]
重构为新的请求类型显示模式  这个问题不存在了
