### ISSUE TITLE
[服务管理]点击配置中心的采购流程图提示错误信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#68]
1.点击配置中心的采购流程图提示错误信息

![1510205370 1](https://user-images.githubusercontent.com/28615156/32589881-19dc5b08-c552-11e7-87b9-ad3b2f872093.jpg)

**Comment by hengwei-ly** [comment]
这个不是bug  这个是当前没有可用流程图的正常显示   没有可用流程图  所以给个警告
