### ISSUE TITLE
[SLA]服务时间设置，在请求中计算出来的逾期时间不正确

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/itsm#7]
[SLA]服务时间设置，在请求中计算出来的逾期时间不正确
![image](https://user-images.githubusercontent.com/22296563/30727550-7d0332a4-9f84-11e7-99d4-96fc494bf6f5.png)

**Comment by hengwei-ly** [comment]
fixed
下面为sla时间计算方法及示例

![qq 20171212124333](https://user-images.githubusercontent.com/26591247/33867817-20767622-df3a-11e7-9a7f-44bede7f9124.png)
