### ISSUE TITLE
[两票管理]在两票管理下面添加一栏子项”缺陷管理”.可以自定义添加缺陷事件项. 

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#78]
1.在两票管理下面添加一栏子项”缺陷管理”.可以自定义添加缺陷事件项.

**Comment by hengwei-ly** [comment]
增加一个功能菜单：缺陷管理，与“两票管理”同级；
功能：
    简单缺陷事件的统计：包含两票中由缺陷引发的事件和自定义事件
实现方式：
   用任务实现：指定任务的自定义字段名；
       显示内容包括：标题；缺陷事件项；发生时间；处理人。。。等
页面有基础功能：增删改查  
        查询就只用模糊查询  标题  和缺陷事件项的查询  就ok

**Comment by hengwei-ly** [comment]
已完成，
自定义字段配置需要手动创建，关联的配置项名称为:
itsm_system_properties_defect
