### ISSUE TITLE
[SLA]服务时间中的所有时间，在页面中备注说明一下它的意思

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/itsm#8]
[SLA]服务时间中的所有时间，在页面中备注说明一下它的意思
![image](https://user-images.githubusercontent.com/22296563/30727555-8d0d6746-9f84-11e7-8e49-a95d790b5dda.png)

**Comment by hengwei-ly** [comment]
![image](https://user-images.githubusercontent.com/26591247/30727642-0f1ebd52-9f85-11e7-9a09-ec32f8c1a752.png)
有备注  有案例

**Comment by xiauye** [comment]
ok
