### ISSUE TITLE
[缺陷管理]选择从数据库中获取的字段时、页面显示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#83]
1.选择从数据库中获取的字段时、页面显示错误

![1514340722 1](https://user-images.githubusercontent.com/28615156/34368400-aa0f06be-eaee-11e7-88ff-94cafd73fc0b.jpg)
![1514340755 1](https://user-images.githubusercontent.com/28615156/34368401-aa46e34a-eaee-11e7-8132-64347a3ab997.jpg)

**Comment by hengwei-ly** [comment]
已解决
