### ISSUE TITLE
[缺陷管理]添加的缺陷任务、只有添加人和Admin可以删除、其余人只有查看权限

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#85]
1.添加的缺陷任务、只有添加人和Admin可以删除、其余人只有查看权限

**Comment by hengwei-ly** [comment]
完成功能改进：
只有创建人和admin账号可以编辑和删除，其他账号只能查看（没有做权限验证，只是根据权限信息隐藏编辑和删除按钮）
