### ISSUE TITLE
[缺陷管理]添加新缺陷后自动生成编号

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#88]
1.添加新缺陷后自动生成编号
2.编号格式 20070001 依次+1
3.在缺陷管理页面显示编号

**Comment by hengwei-ly** [comment]
已完成
新增缺陷的编号是在当前已存在的最大编号基础上+1 ，如果跨年新增缺陷，编号重置为当前年份+0001 
目前一年内如果新增9999 条缺陷，再新增的时候会变为年份+1

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，close处理。
