### ISSUE TITLE
[请求]选择其他请求进行进行编辑或者其他操作，都会直接返回到我的未解决请求页面

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/itsm#9]
[请求]选择其他请求进行进行编辑或者其他操作，都会直接返回到我的未解决请求页面
![image](https://user-images.githubusercontent.com/22296563/30788833-84e92b3a-a1d3-11e7-93b7-d67e52bb0ca5.png)

**Comment by hengwei-ly** [comment]
已修改，现在除非一些特殊的请求（比如用web访问，或者跳转到发邮件），其他的页面返回都会回到对应条件的查询界面
