### ISSUE TITLE
[华东电网]请求流程关联两票、两票流程未关闭、请求流程无法关闭

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#95]
请求流程关联两票、两票流程未关闭、请求流程无法关闭

**Comment by hengwei-ly** [comment]
已完成，在任务中可以添加三种任务，普通任务、关联请求、和独立请求；
普通任务为原来的任务，没有流程
独立请求为请求，可以理解为当前请求的子请求，包含流程，但与当前请求没有硬关联，流程间相互不影响
关联请求为请求，拥有关联当前请求的流程，父请求流转中必须保证所有关联子请求已关闭，否则父请求无法执行下一步处理（但是如果设置了告警恢复自动关闭请求，则没有这个限制，父请求会直接关闭，子请求状态不做改变）

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180123_3203_x64.exe  版本确认，close处理。
