### ISSUE TITLE
[华东电网]巡检和告警提出请求是带上设备源、后续处理中显示设备源

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#96]
巡检和告警提出请求是带上设备源、后续处理中显示设备源

**Comment by hengwei-ly** [comment]
设备源的显示由通知规则处定义  可以定义在描述中

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180123_3203_x64.exe  版本确认，close处理。
