### ISSUE TITLE
[华东电网]告警的请求根据设备类型指定给某个人或者某个组的成员来处理

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/itsm#97]
告警的请求根据设备类型指定给某个人或者某个组的成员来处理

**Comment by hengwei-ly** [comment]
已完成，需要配置配置文件,如果在配置文件里面找不到对应的用户组id  则按照流程图上指示的步骤进行

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180123_3203_x64.exe  版本确认，close处理。
